services:
  nodedev:
    build:
        context: ./node
        dockerfile: dockerfile
    container_name: nodedev
    volumes:
      - ./node:/var/app
    entrypoint: sh -c "npm install && node index.js"
    networks:
      - node-net
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysqldev
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3

  nginx:
    build:
        context: ./nginx
        dockerfile: dockerfile
    container_name: nginxdev
    networks:
      - node-net
    ports:
      - "8080:80"
    depends_on:
      - nodedev

networks:
  node-net:
    driver: bridge